### ISSUE TITLE
Printf and serial send not working?

### ISSUE THREAD

**Issue by dvcomp** [Wiznet/WIZ550web#10]
Printf (debug messages) and serial send (from web page) not working. Or just for me?

**Comment by dvcomp** [comment]
Still the same (no tx from main app). Are there any difference between  serial FW load and STLink? (I use the later one)

Happy New Year for everyone!

**Comment by bingdo** [comment]
Hi.

What does "STLink" mean? If that means the JTAG or SWD interface, we do not support that.
You can use the flash loader demonstrator tool when downloading.
Refer to http://www.st.com/web/catalog/tools/FM147/CL1794/SC961/SS1533/PF257525

And I have a question. How did you use a STLink in WIZ550web?

Thanks.

**Comment by bingdo** [comment]
If you have no more question, I'd like to close this issue.
Thanks.
